#include <iostream>


/*FIRST STEP: DEFINE CLASSES AND UC'S
SECOND STEP: DEFINE STUDENTS
THIRD STEP: FIND A WAY TO GET THE SCHEDULES AND DO THE MANAGEMENT FUNCTION
    3.1: CREATE A TIMESPACE CLASS
    3.2: CREATE A FILE ONLY FOR SCHEDULE MANAGEMENT
FOURTH STEP: VERIFY EVERYTHING AND CORRECT IT
FIFTH STEP: ADD NEW FUNCTIONS


 TODO: THIRD STEP FORWARD


*/
int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
